on: [push, pull_request]
name: Build and Test
jobs:
  test:
    continue-on-error: true
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x, 1.20.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      run: make test
    - name: Build
      run: make build